title: Github Pages codelab 
author: Alex Kim
email: top@secret.example.com
description: > # this means to ignore newlines until "baseurl:"
  Just going through the codelab.

# social links
twitter_username: topsecret # DO NOT include the @ character, or else the build will fail!
github_username: Alex-K1m # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
